export const CREATE_PROJECT = 'CREATE_PROJECT'
export const CREATE_PROJECT_ERROR = 'CREATE_PROJECT_ERROR'
export const CREATE_PROJECT_LOADING = 'CREATE_PROJECT_LOADING'

export const LOG_IN = 'LOG_IN'
export const LOG_IN_ERROR = 'LOG_IN_ERROR'
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS'
